spring:
  datasource:
    name: defaultDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lightning?useUnicode=true&useInformationSchema=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Mysql@2024
  jpa:
    show-sql: true
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
knife4j:
  production: false
